services:
  frontend:
    build: ./frontend
    ports:
      - "${TRACKR_PORT:-8080}:${TRACKR_PORT:-8080}"
    env_file:
      - ./frontend/.env
  backend:
    build: ./backend
    ports:
      - "${TRACKR_API_PORT:-5000}:${TRACKR_API_PORT:-5000}"
    env_file:
      - ./backend/.env
